config:
  prefix: '&b&lVanish &8| &7'
  vanish_on: 'You are now in &bVanish§7.'
  vanish_off: 'You are no longer in &bVanish&7.'
  vanish_other_on: 'The Player &b%player% &7is now in Vanish.'
  vanish_other_off: 'The Player &b%player% &7is no longer in Vanish.'
  not_found: 'The Player &b%not_player% &7was not found!'
  nopermissions: '&cNo Permissions!'
  permission: 'system.vanish'
  use: 'Use &b/vanish <Name>'